name: Execution sequential

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - name: Execute ls -la
      run: ls -la
    - name: Check if README exist
      run: sh -f README.md  && echo "Found" || echo "Not found"
    - name: Check if Makefile exist
      run: sh -f Makefile.md && echo "Found" || echo "Not found"
    - name: clean project
      run: make clean
    - name: compile the project
      run: make
    - name: Create a 200x200 matrix file
      run: ./gmat 200 200
    - name: Create a 2000x2000 matrix file
      run: ./gmat 2000 2000
    - name: Execute main_omp with a 200x200 matrix
      run: ./main_omp 200x200-mat.map 200x200-mat.map 2
    - name: Execute main_omp with a 2000x2000 matrix
      run: ./main_omp 2000x2000-mat.map 2000x2000-mat.map 2
    - name: Execute main_omp with a 2000x2000 matrix and 4 threads
      run: ./main_omp 2000x2000-mat.map 2000x2000-mat.map 4
