name: Execution sequential

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - name: Execute ls -la
      run: ls -la
    - name: Check if README exist
      run: sh -f README.md  && echo "Found" || echo "Not found"
    - name: Check if Makefile exist
      run: sh -f Makefile.md && echo "Found" || echo "Not found"
    - name: clean project
      run: make clean
    - name: compile the project
      run: make
    - name: Create a 1000x1000 matrix file
      run: ./gmat 1000 1000
    - name: Create a 1500x1500 matrix file
      run: ./gmat 1500 1500
    - name: Execute main_omp with a 1000x1000 matrix
      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map 2
    - name: Execute main_omp with a 1500x1500 matrix
      run: ./main_omp 1500x1500-mat.map 1500x1500-mat.map 2
    - name: Execute main_omp with a 2000x2000 matrix and 4 threads
      run: ./main_omp 1500x1500-mat.map 1500x1500-mat.map 4
