name: Parallelism

on: [push]
    
jobs:
 
  aspect1: 
     runs-on: ubuntu-latest
     name: Aspect1- Check for source and help files.
     steps:
       - uses: actions/checkout@v1
       - name: Execute ls -la
         run: ls -la
       - name: Check if README exist
         run: sh -f README.md  && echo "Found" || echo "Not found"
       - name: Check if Makefile exist
         run: sh -f Makefile.md && echo "Found" || echo "Not found"
          # Fontes da biblioteca (matriz, tools, matriz-operacoes)
          # Fontes do programa principal (main_matriz.c e/ou main_matriz-bloco.c)
  build:
    name: Build project executing make command
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean project
      run: make clean
    - name: compile the project
      run: make
    - name: Upload gmat-file
      uses: actions/upload-artifact@v1
      with:
          name: gmat-file
          path: gmat
    
  matrix100:
    needs: [build]
    name: Create a 100x100 matrix 
    runs-on: ubuntu-latest
    
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: gmat-file
    - name: Change permission
      run: sh -c "sudo chmod -R 777 ./gmat-file"
    - name: Create a 100x100 matrix file
      run: ./gmat-file/gmat 100 100
    - name: Upload map file for aspect2
      uses: actions/upload-artifact@v1
      with:
          name: gmat100
          path: 100x100-mat.map

  matrix1000:
    needs: [build]
    name: Create a 1000x1000 matrix 
    runs-on: ubuntu-latest
    
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: gmat-file
    - name: Create a matrix file
      run: ./gmat-file/gmat 1000 1000
      
  aspect2:
    needs: [build, matrix100]
    name: Execute main_omp with a 100x100 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: gmat100
    - name: Create a matrix file
      run: main_omp 100x100-mat.map 100x100-mat.map 2

  aspect3:
    needs: [build, matrix1000]
    name: Execute main_omp with a 1000x1000 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Execute main omp
      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map 2

  aspect4:
    needs: [build, matrix1000]
    name: Execute main_omp with a 1000x1000 matrix and check speedup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Execute main omp
      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map 4
