name: Parallel Execution 

on: [push]
    
jobs:
 
  aspect1: 
     runs-on: ubuntu-latest
     name: Aspect1- Check for source and help files.
     steps:
       - uses: actions/checkout@v1
       - name: Execute ls -la
         run: ls -la
       - name: Check if README exist
         run: sh -f README.md  && echo "Found" || echo "Not found"
       - name: Check if Makefile exist
         run: sh -f Makefile.md && echo "Found" || echo "Not found"
          # Fontes da biblioteca (matriz, tools, matriz-operacoes)
          # Fontes do programa principal (main_matriz.c e/ou main_matriz-bloco.c)
  build:
    name: Build project executing make command
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean project
      run: make clean
    - name: compile the project
      run: make
    - name: Upload gmat-folder
      uses: actions/upload-artifact@v1
      with:
          name: gmat-folder
          path: gmat
    - name: Upload main_omp
      uses: actions/upload-artifact@v1
      with:
          name: main_omp-folder
          path: main_omp
    
  matrix1000:
    needs: [build]
    name: Create a 1000x1000 matrix 
    runs-on: ubuntu-latest
    
    steps:
    - name: Download gmat-folder
      uses: actions/download-artifact@v1
      with:
        name: gmat-folder
    - name: Change permission
      run: sh -c "sudo chmod -R 777 ./gmat-folder"
    - name: Create a 1000x1000 matrix file
      run: ./gmat-folder/gmat 1000 1000
    - name: Upload map file for aspect2
      uses: actions/upload-artifact@v1
      with:
          name: gmat1000-folder
          path: 1000x1000-mat.map

  matrix1500:
    needs: [build]
    name: Create a 1500x1500 matrix 
    runs-on: ubuntu-latest
    
    steps:
    - name: Download gmat-folder
      uses: actions/download-artifact@v1
      with:
        name: gmat-folder
    - name: Change gmat-folder permission
      run: sh -c "sudo chmod -R 777 ./gmat-folder"
    - name: Create a matrix file
      run: ./gmat-folder/gmat 1500 1500
    - name: Upload map file for aspect2
      uses: actions/upload-artifact@v1
      with:
          name: gmat1500-folder
          path: 1500x1500-mat.map

  aspect2:
    needs: [build, matrix1000]
    name: Execute main_omp with a 1000x1000 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download gmat1000-folder
      uses: actions/download-artifact@v1
      with:
        name: gmat100-folder
    - name: Change gmat1000-folder permission
      run: sh -c "sudo chmod -R 777 ./gmat1000-folder"
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: main_omp-folder
    - name: Change permission
      run: sh -c "sudo chmod -R 777 ./main_omp-folder"
    - name: Execute main_omp with a 1000x1000 matrix
      run: ./main_omp-folder/main_omp ./gmat1000-folder/1000x1000-mat.map ./gmat1000-folder/1000x1000-mat.map 2

  aspect3:
    needs: [build, matrix1500]
    name: Execute main_omp with a 1500x1500 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download gmat1500-folder
      uses: actions/download-artifact@v1
      with:
        name: gmat1500-folder
    - name: Change gmat1500-folder permission
      run: sh -c "sudo chmod -R 777 ./gmat1500-folder"
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: main_omp-folder
    - name: Change permission
      run: sh -c "sudo chmod -R 777 ./main_omp-folder"
    - name: Execute main_omp with a 1500x1500 matrix
      run: ./main_omp-folder/main_omp ./gmat1500-folder/1500x1500-mat.map ./gmat1500-folder/1500x1500-mat.map 2

  aspect4:
    needs: [build, matrix1500]
    name: Execute main_omp with a 1500x1500 matrix and check speedup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download gmat1500-folder
      uses: actions/download-artifact@v1
      with:
        name: gmat1500-folder
    - name: Change gmat1500-folder permission
      run: sh -c "sudo chmod -R 777 ./gmat1000-folder"
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: main_omp-folder
    - name: Change permission
      run: sh -c "sudo chmod -R 777 ./main_omp-folder"
    - name: Execute main_omp with a 1500x1500 matrix and 4 threads
      run: ./main_omp-folder/main_omp ./gmat1500-folder/1500x1500-mat.map ./gmat1500-folder/1500x1500-mat.map 4
