name: Parallel Execution 2

on: [push]
    
jobs:
 
  aspect1: 
     runs-on: ubuntu-latest
     name: Aspect1- Check for source and help files.
     steps:
       - uses: actions/checkout@v1
       - name: Execute ls -la
         run: ls -la
       - name: Check if README exist
         run: sh -f README.md  && echo "Found" || echo "Not found"
       - name: Check if Makefile exist
         run: sh -f Makefile.md && echo "Found" || echo "Not found"
          # Fontes da biblioteca (matriz, tools, matriz-operacoes)
          # Fontes do programa principal (main_matriz.c e/ou main_matriz-bloco.c)

  aspect2:
    name: Execute main_omp with a 100x100 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile the project
      run: make
    - name: Create a matrix file
      run: ./gmat 100 100
    - name: Execute main_omp with a 100x100 matrix
      run: ./main_omp 100x100-mat.map 100x100-mat.map 2

  aspect3:
    name: Execute main_omp with a 1000x1000 matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile the project
      run: make
    - name: Create a matrix file
      run: ./gmat 1000 1000
    - name: Execute main_omp with a 1000x1000 matrix
      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map 2

  aspect4:
    name: Execute main_omp with a 1000x1000 matrix and check speedup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile the project
      run: make
    - name: Create a matrix file
      run: ./gmat 1000 1000
    - name: Execute main_omp with a 1000x1000 matrix
      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map 4
